channels:
- conda-forge
dependencies:
- python=3.8.15
- pip<=21.0.1
- pip:
  - mlflow
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - fsspec==2023.4.0
  - geopandas==0.11.1
  - pydeprecate==0.3.2
  - python-dotenv==0.20.0
  - pytorch-lightning==1.6.3
  - rtree==1.0.1
  - scikit-learn==1.1.1
  - tensorboard==2.12.2
  - torch==1.13.0
  - torchmetrics==0.11.4
  - torchvision==0.14.0
  - tqdm==4.64.1
name: mlflow-env
